### ISSUE TITLE
double prompt on password

### ISSUE THREAD

**Issue by SoreGums** [BrandonT42/Shell-Wallet#1]
http://youtu.be/rT1aUAkvKsU?hd=1

open default or file > open - gets a double prompter dialog for password.
wallet opens.

**Comment by BrandonT42** [comment]
Top textbox is for entering your password, bottom one is to type again as a confirmation so you don't have to sit through a verification and whatnot if you typed it wrong on accident. Not a huge issue, but it's handy for me personally. If the presence of two textboxes is not the issue, I am still a bit confused.

**Comment by SoreGums** [comment]
OK i understand your point, so you're saying the turnaround for checking the password is slow, so double prompt up front?

That is not really how anything else works though, maybe this needs to be an option?

if someone is using a password manager, having to double paste is again not how anything else works ;)

**Comment by BrandonT42** [comment]
Fair point, option it is :P

**Comment by BrandonT42** [comment]
Made this optional in the latest commit
